### PR TITLE
Camunda-Dropwizard integration "out of the box"

### PR DESCRIPTION
**Pull request by chrisphe**
Recently did some work to integrate these in a working application.

Changes in this PR:
- Setting of JdbcMaxActiveConnections, History Level, and whether DB Schema should be updated
- Allow configuration of which processes should be deployed from BPMN and which should be started on boot automatically
- Integrated a RestProcessEngine provider which delegates to Camunda's ProcessEngines
- Provided an application implementation which performs necessary registration and bootstrapping
- Provided a StartProcess task
- Ensured proper registration using the JDK6 SPI interface

### CODE REVIEW

**Comment by jangalinski** [comment]
Hi Chris ...  I almost forgot about this project, because the last month I supported https://github.com/camunda/camunda-spring-boot-starter/ instead. But I am happy that it gets interest (and PRs). Maybe we could move this to be an alternative community extension hosted by camunda when it gets up and running smoothly. 

That being said: I just had a first small glimpse at your code, will definitely have a deeper look tonight. 

First thing I already noticed: I do not like the logging deps you introduced. It should be enough to rely on slf4j-api, siple is an implementation the client would choose. And why would we need commons-logging?

cu
Jan

**Comment by chrisphe** [comment]
Hi, actually, those are not dependencies, they are exclusions to avoid slf4j-simple or commons-logging being brought in transitively :-)

**Comment by chrisphe** [comment]
I am also looking at Spring Boot as an alternative, by the time you integrate Camunda, Spring and Dropwizard, Spring Boot may be quite a bit the simpler choice

**Comment by chrisphe** [comment]
Actually, I think the RestEasy can be removed. Will update the PR

**Comment by jangalinski** [comment]
My bad ... I will have a look at the whole package in my IDE instead of just browsing red and green lines ... promised :-)

**Comment by chrisphe** [comment]
No worries. I don't think the rest-easy needed to be there at all (my bad) so I've updated the PR

**Comment by chrisphe** [comment]
Hi, any plans to apply this PR? Thanks Chris

**Comment by jangalinski** [comment]
done, sorry for keeping you waiting

**Pull request merged**
